language: php
php:
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - git config --global user.email "mail@example.com"
  - git config --global user.name "Composer Update"
  - composer install --prefer-dist --no-interaction

script:
  - composer --version
  - if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then composer global require o0h/composer-update-request:dev-wip@dev -vvv && composer update -vvv; fi
